Fixing command to checkout the right CakePHP version on Travis.
Travis output says:
error: pathspec '2.2.7' did not match any file(s) known to git.
The command "git checkout $CAKE_VERSION" failed and exited with 1 during before_script.

That's because when cloning with '--depth 1' it doesn't retrieves branches/tags references (on git 1.8.1 and newer).